export const ADD_To_CART = 'ADD_To_CART';
export const VIEW_CART='VIEW_CART';
export const SEARCH = 'SEARCH';
export const SELECTION_FILTER ='SELECTION_FILTER';
export const DELETE_ITEM ='DELETE_ITEM';
export const AUTH_USER = 'AUTH_USER';
export const INCREASE_QUANTITY= 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'